[workspace]
resolver = "2"
members = [
    "core",
    "frontend",
    "run-wasm",
    "file-dialog",
    "egui-osstr",
]
default-members = [
    "core",
    "frontend",
    "file-dialog",
    "egui-osstr",
]
